console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")
console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")
console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")
console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")
console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")
console.log("venkatesh")
console.log("practiceing for future")
console.log("mdnsx")